# -*- coding: utf-8 -*-
"""sh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C2piNAUz4qIApMriM7_zcRoNQKzPNNwU
"""

mkdir data
cd data
wget https://nlp.stanford.edu/projects/snli/snli_1.0.zip
unzip snli_1.0.zip