# -*- coding: utf-8 -*-
"""preprocess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ynXiyfc4wEa17SYjYAnW0LlDTQFmJ2Dz
"""




data_dir_train="snli_1.0_train.txt"
label_dict={'entailment': 0, 'contradiction': 1, 'neutral': 2}
with open(data_dir_train, 'r') as f:
  texts=[row.split('\t') for row in f.readlines()[1:]]              
  premise=[row[5] for row in texts if row[0] in label_dict]
  hypothesis=[row[6] for row in texts if row[0] in label_dict]
  labels=[row[0] for row in texts if row[0] in label_dict]


with open('preprocessed_snli_train.txt', 'w') as f:
  for i in range(len(labels)):
    f.write(premise[i]+'\t')
    f.write(hypothesis[i]+'\t')
    f.write(labels[i]+'\n')
#print(premise)
#print(hypothesis)
#print(labels)



data_dir_test="snli_1.0_test.txt"
label_dict={'entailment': 0, 'contradiction': 1, 'neutral': 2}
with open(data_dir_test, 'r') as f:
  texts=[row.split('\t') for row in f.readlines()[1:]]              
  premise=[row[5] for row in texts if row[0] in label_dict]
  hypothesis=[row[6] for row in texts if row[0] in label_dict]
  labels=[row[0] for row in texts if row[0] in label_dict]


with open('preprocessed_snli_test.txt', 'w') as f:
  for i in range(len(labels)):
    f.write(premise[i]+'\t')
    f.write(hypothesis[i]+'\t')
    f.write(labels[i]+'\n')

